"version": "3.9"
"services":
  "db":
    "image": "mongo"
    "volumes":
      - "data:/data/db"
    "command": " --quiet --wiredTigerCacheSizeGB 0.5"
    "logging":
      "driver": "local"
  "cache":
    "image": "redis"
    "volumes":
      - "redisdata:/data"
    "logging":
      "driver": "local"
  "loader":
    "build": "loadBulk"
    "volumes":
      - "downloads:/loadBulk/downloads"
    "environment":
      "MONGO_URL": "mongodb://db"
  "endpoints":
    "build": "."
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://cache:6379"
    "env_file":
      - "../.api.env"
    "ports":
      - "3000:3000"
"volumes":
  "data": null
  "downloads": null
  "redisdata": null
