"version": "3.9"
"services":
  "db":
    "build": "databases/mongo"
    "volumes":
      - "data:/data/db"
    "logging":
      "driver": "local"
    "networks":
      - "officers"
    ports:
      - "27017:27017"
  "red":
    "build": "databases/redis"
    "volumes":
      - "redisdata:/data"
    "logging":
      "driver": "local"
    "networks":
      - "officers"
  "loader":
    "build":
      "dockerfile": "Loader.Dockerfile"
    "depends_on":
      - "db"
    "volumes":
      - "downloads:/loadBulk/downloads"
    "environment":
      "MONGO_URL": "mongodb://db"
      "REDIS_URL": "redis://red:6379"
      "LOKI_URL": "http://loki:3100"
    "networks":
      - "officers"
      - "companiesv2_metrics"
  "updater-worker":
    "build":
      "dockerfile": "Updater.Dockerfile"
    command: node job/worker.js
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "LOKI_URL": "http://loki:3100"
      SFTP_KEY_FILENAME: "/.ssh/key"
    volumes:
      - source: $HOST_SFTP_KEY_LOCATION
        type: bind
        target: /.ssh/key
      - /home/node/.pnpm-store
      - "downloads:/officers/streamUpdater/downloads"
    "env_file":
      - "../.api.env"
      - "./.sftp.env"
    "networks":
      - "officers"
      - "companiesv2_metrics"
  "updater-scheduler":
    "build":
      "dockerfile": "Updater.Dockerfile"
    command: node job/scheduler.js
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "LOKI_URL": "http://loki:3100"
    "env_file":
      - "../.api.env"
    volumes:
      - /home/node/.pnpm-store
    "networks":
      - "officers"
      - "companiesv2_metrics"
  "web-service":
    "hostname": "officers-web-service"
    "build":
      "dockerfile": "WebService.Dockerfile"
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "AUTH_URL": "http://auth-service:3000"
      "LOKI_URL": "http://loki:3100"
    "env_file":
      - "../.api.env"
    "networks":
      - "companiesv2_microservices"
      - "officers"
      - "companiesv2_metrics"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
  "officers": null
"volumes":
  "data": null
  "downloads": null
  "redisdata": null
