"version": "3.9"
"services":
  "db":
    "build": "databases/mongo"
    "volumes":
      - "data:/data/db"
    "logging":
      "driver": "local"
    "networks":
      - "personsWithSignificantControl"
    deploy:
      resources:
        limits:
          memory: 1.2GB
  "red":
    "build": "databases/redis"
    "volumes":
      - "redisdata:/data"
    "logging":
      "driver": "local"
    "networks":
      - "personsWithSignificantControl"
  "loader":
    "build":
      "dockerfile": "Loader.Dockerfile"
    "depends_on":
      - "db"
    "volumes":
      - "downloads:/personsWithSignificantControl/loadBulk/downloads"
    "environment":
      "MONGO_URL": "mongodb://db"
      "REDIS_URL": "redis://red:6379"
      "LOKI_URL": "http://loki:3100"
    "networks":
      - "personsWithSignificantControl"
      - "companiesv2_metrics"
  "updater":
    "build":
      "dockerfile": "Updater.Dockerfile"
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "LOKI_URL": "http://loki:3100"
    "env_file":
      - "../.api.env"
    "networks":
      - "personsWithSignificantControl"
      - "companiesv2_metrics"
  "web-service":
    "hostname": "persons-with-significant-control-web-service"
    "build":
      "dockerfile": "WebService.Dockerfile"
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "AUTH_URL": "http://auth-service:3000"
      "LOKI_URL": "http://loki:3100"
    "env_file":
      - "../.api.env"
    "networks":
      - "companiesv2_microservices"
      - "personsWithSignificantControl"
      - "companiesv2_metrics"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
  "personsWithSignificantControl": null
"volumes":
  "data": null
  "downloads": null
  "redisdata": null
