"version": "3"
"services":
  "registered-office-address":
    "build": "registeredOfficeAddress"
    "ports":
      - "3000:3001"
  "company-profile":
    "build": "companyProfile"
    "ports":
      - "3000:3002"
  "search":
    "build": "search"
    "ports":
      - "3000:3003"
  "officers":
    "build": "officers"
    "ports":
      - "3000:3004"
  "registers":
    "build": "registers"
    "ports":
      - "3000:3005"
  "charges":
    "build": "charges"
    "ports":
      - "3000:3006"
  "filing-history":
    "build": "filingHistory"
    "ports":
      - "3000:3007"
  "insolvency":
    "build": "insolvency"
    "ports":
      - "3000:3008"
  "exemptions":
    "build": "exemptions"
    "ports":
      - "3000:3009"
  "officer-disqualifications":
    "build": "officerDisqualifications"
    "ports":
      - "3000:3010"
  "officer-appointments":
    "build": "officerAppointments"
    "ports":
      - "3000:3011"
  "ukestablishments":
    "build": "UKEstablishments"
    "ports":
      - "3000:3012"
  "persons-with-significant-control":
    "build": "personsWithSignificantControl"
    "ports":
      - "3000:3013"
