"version": "3.7"
"services":
  "gateway":
    "image": "caddy"
    "volumes":
      - "./Caddyfile:/etc/caddy/Caddyfile"
    "ports":
      - "3000:80"
    "networks":
      - "companiesv2_microservices"
      - "companiesv2_metrics"
    "logging":
      "driver": "local"
  "auth-db":
    "image": "redis"
    "networks":
      - "companiesv2_auth"
    "logging":
      "driver": "local"
    "volumes":
      - "auth_db:/data"
  "auth-service":
    "build": "auth"
    "networks":
      - "companiesv2_auth"
      - "companiesv2_microservices"
    "logging":
      "driver": "local"
    "environment":
      "AUTH_DB_URL": "auth-db"
  "metrics":
    "build": "monitoring/prometheus"
    "logging":
      "driver": "local"
    "ports":
      - "9090:9090"
    "networks":
      - "companiesv2_metrics"
    "environment":
      "CADDY_METRICS_URL": "http://gateway:2022"
  "loki":
    "build": "monitoring/loki"
    "logging":
      "driver": "local"
    "networks":
      - "companiesv2_metrics"
  "grafana":
    "build": "monitoring/grafana"
    "ports":
      - "9091:3000"
    "logging":
      "driver": "local"
    "networks":
      - "companiesv2_metrics"
    "volumes":
      - "grafana_data:/var/lib/grafana"
      - "/var/log/grafana"
      - "./monitoring/grafana/dashboards:/etc/grafana/dashboards"
    "environment":
      "LOKI_URL": "http://loki:3100"
      "METRICS_URL": "http://metrics:9090"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
"volumes":
  "shared_mongo":
    "external": true
  "auth_db":
    "external": true
  "grafana_data": null
  "loki_data": null
