"version": "3.7"
"services":
  "registered-office-address":
    "build": "registeredOfficeAddress/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "company-profile":
    "build": "companyProfile/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "search":
    "build": "search/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "officers":
    "build": "officers/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "registers":
    "build": "registers/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "charges":
    "build": "charges/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "filing-history":
    "build": "filingHistory/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "insolvency":
    "build": "insolvency/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "officer-disqualifications":
    "build": "officerDisqualifications/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "officer-appointments":
    "build": "officerAppointments/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "ukestablishments":
    "build": "UKEstablishments/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "persons-with-significant-control":
    "build": "personsWithSignificantControl/webService"
    "networks":
      - "companiesv2_microservices"
    "env_file":
      - ".env"
    "logging":
      "driver": "local"
  "gateway":
    "image": "caddy"
    "volumes":
      - "./Caddyfile:/etc/caddy/Caddyfile"
    "ports":
      - "3000:80"
    "networks":
      - "companiesv2_microservices"
      - "companiesv2_metrics"
    "logging":
      "driver": "local"
  "auth-db":
    "image": "redis"
    "networks":
      - "companiesv2_auth"
    "logging":
      "driver": "local"
    "volumes":
      - "auth_db:/data"
  "auth-service":
    "build": "auth"
    "networks":
      - "companiesv2_auth"
      - "companiesv2_microservices"
    "logging":
      "driver": "local"
    "environment":
      "AUTH_DB_URL": "auth-db"
  "metrics":
    "image": "prom/prometheus"
    "logging":
      "driver": "local"
    "volumes":
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    "ports":
      - "9090:9090"
    "networks":
      - "companiesv2_metrics"
  "shared-mongo":
    "image": "mongo"
    "logging":
      "driver": "local"
    "networks":
      - "companiesv2_microservices"
    "volumes":
      - "shared_mongo:/data/db"
  "shared-redis":
    "image": "redis"
    "logging":
      "driver": "local"
    "networks":
      - "companiesv2_microservices"
    "volumes":
      - "/data"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
"volumes":
  "shared_mongo":
    "external": true
  "auth_db":
    "external": true
