"version": "3.7"
"services":
  "gateway":
    "image": "caddy"
    "volumes":
      - "./Caddyfile:/etc/caddy/Caddyfile"
    "ports":
      - "3000:80"
    "networks":
      - "companiesv2_microservices"
      - "companiesv2_metrics"
    "logging":
      "driver": "local"
  "auth-db":
    "image": "redis"
    "networks":
      - "companiesv2_auth"
    "logging":
      "driver": "local"
    "volumes":
      - "auth_db:/data"
  "auth-service":
    "build": "auth"
    "networks":
      - "companiesv2_auth"
      - "companiesv2_microservices"
    "logging":
      "driver": "local"
    "environment":
      "AUTH_DB_URL": "auth-db"
  "metrics":
    "image": "prom/prometheus"
    "logging":
      "driver": "local"
    "volumes":
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    "ports":
      - "9090:9090"
    "networks":
      - "companiesv2_metrics"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
"volumes":
  "shared_mongo":
    "external": true
  "auth_db":
    "external": true
