"version": "3"
"services":
  "registered-office-address":
    "build": "registeredOfficeAddress"
    "networks":
      - "microservices"
  "company-profile":
    "build": "companyProfile"
    "networks":
      - "microservices"
  "search":
    "build": "search"
    "networks":
      - "microservices"
  "officers":
    "build": "officers"
    "networks":
      - "microservices"
  "registers":
    "build": "registers"
    "networks":
      - "microservices"
  "charges":
    "build": "charges"
    "networks":
      - "microservices"
  "filing-history":
    "build": "filingHistory"
    "networks":
      - "microservices"
  "insolvency":
    "build": "insolvency"
    "networks":
      - "microservices"
  "exemptions":
    "build": "exemptions"
    "networks":
      - "microservices"
  "officer-disqualifications":
    "build": "officerDisqualifications"
    "networks":
      - "microservices"
  "officer-appointments":
    "build": "officerAppointments"
    "networks":
      - "microservices"
  "ukestablishments":
    "build": "UKEstablishments"
    "networks":
      - "microservices"
  "persons-with-significant-control":
    "build": "personsWithSignificantControl"
    "networks":
      - "microservices"
  "gateway":
    "image": "caddy"
    "volumes":
      - "./Caddyfile:/etc/caddy/Caddyfile"
    "ports":
      - "3000:80"
    "networks":
      - "microservices"
"networks":
  "microservices":
    "driver": "bridge"
