"version": "3.9"
"services":
  "db":
    "build": "databases/mongo"
    "volumes":
      - "data:/data/db"
    "logging":
      "driver": "local"
    "networks":
      - "search"
  "cache":
    "build": "databases/redis"
    "volumes":
      - "redisdata:/data"
    "logging":
      "driver": "local"
    "networks":
      - "search"
  "loader":
    "build": "loadBulk"
    "depends_on":
      - "db"
    "volumes":
      - "downloads:/loadBulk/downloads"
    "environment":
      "MONGO_URL": "mongodb://db"
    "networks":
      - "search"
  "updater":
    "build": "streamUpdater"
    "depends_on":
      - "db"
      - "cache"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://cache:6379"
    "env_file":
      - "../.api.env"
    "networks":
      - "search"
  "web-service":
    "build": "webService"
    "depends_on":
      - "db"
      - "cache"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://cache:6379"
      "AUTH_URL": "http://auth-service:3000"
    "env_file":
      - "../.api.env"
    "ports":
      - "3000:3000"
    "networks":
      - "companiesv2_microservices"
      - "search"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
  "search": null
"volumes":
  "data": null
  "downloads": null
  "redisdata": null
