"version": "3.9"
"services":
  "db":
    "build": "databases/mongo"
    "volumes":
      - "data:/data/db"
    "logging":
      "driver": "local"
    "networks":
      - "registers"
  "red":
    "build": "databases/redis"
    "volumes":
      - "redisdata:/data"
    "logging":
      "driver": "local"
    "networks":
      - "registers"
  "loader":
    "build":
      "dockerfile": "Loader.Dockerfile"
    "depends_on":
      - "db"
    "volumes":
      - "downloads:/loadBulk/downloads"
    "environment":
      "MONGO_URL": "mongodb://db"
      "REDIS_URL": "redis://red:6379"
    "networks":
      - "registers"
  "updater":
    "build":
      "dockerfile": "Updater.Dockerfile"
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
    "env_file":
      - "../.api.env"
    "networks":
      - "registers"
  "web-service":
    "build":
      "dockerfile": "WebService.Dockerfile"
    "depends_on":
      - "db"
      - "red"
    "environment":
      "MONGO_URL": "mongodb://db:27017"
      "REDIS_URL": "redis://red:6379"
      "AUTH_URL": "http://auth-service:3000"
    "env_file":
      - "../.api.env"
    "ports":
      - "3000:3000"
    "networks":
      - "companiesv2_microservices"
      - "registers"
"networks":
  "companiesv2_microservices":
    "external": true
  "companiesv2_auth":
    "external": true
  "companiesv2_metrics":
    "external": true
  "registers": null
"volumes":
  "data": null
  "downloads": null
  "redisdata": null
