name: 'build-typescript'
on: # rebuild any PRs and any branch changes
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: 'services/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm -r install
        working-directory: services
      - name: Build all workspace packages
        run: pnpm -r run build
        working-directory: services
      - name: Build monolith
        run: pnpm run build
        working-directory: services
